### ISSUE TITLE
Simple small pathway - badly stretched layout

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/chilay-sbgn#1]
To test and fix, one can use the SBGN returned by [this PC query](http://beta.pathwaycommons.org/pc2/get?format=sbgn&uri=http%3A%2F%2Fpathwaycommons.org%2Fpc2%2FPathway_78c1a86e97b8823afd57833065c64f65).

**Comment by IgorRodchenkov** [comment]
@ozgunbabur  @ugurdogrusoz @begumgenc (great if'd help with this here ;))

**Comment by IgorRodchenkov** [comment]
It's slightly better now (after layout fix in chilay-sbgn, Paxtoools, and PC9 - rebuilt/restarted)

**Comment by IgorRodchenkov** [comment]
Ah, interesting... I used e.g., http://www.cs.bilkent.edu.tr/~ivis/SBGNViz_daily/ to load that sbgn file and have been clicking on the button to re-apply COSE layout 10-20 times... 90% times this results in a good-looking layout, but sometimes I was getting the ugly stretched one!

**Comment by ugurdogrusoz** [comment]
@IgorRodchenkov with our recent improvement in layout (currently available in JS version only since we're still finalizing this improvement), this map no longer stretches like this once every few iterations. In fact, I tried to lay out this map about 25 times, no bad layout. Improved layout is here (and released on npm): http://www.cs.bilkent.edu.tr/~ivis/ChiSE_daily/#

**Comment by ugurdogrusoz** [comment]
After the latest improvement:
![get](https://user-images.githubusercontent.com/3874988/28873132-07286afc-7795-11e7-9bb8-ce6b8663fb56.png)
See here:
https://github.com/iVis-at-Bilkent/chilay/releases/tag/v2.0.0
or here:
https://github.com/PathwayCommons/chilay-sbgn/pull/3/files
@IgorRodchenkov closing the issue, let me know if you disagree.

**Comment by IgorRodchenkov** [comment]
[issue1-out.tar.gz](https://github.com/PathwayCommons/chilay-sbgn/files/1194440/issue1-out.tar.gz)
After I merged the PR #3, rebuilt/redeployed chilay-sbgn 3.0.1-SNAPSHOT, rebuildtPaxtools (sbgn-converter depends on chilay-sbgn), and rebuilt and restarted my test Pathway Commons (PC9) instance, the same test query (see above) now returns SBGN-ML having x="NaN" y="NaN" in many cases (I bet, division by zero was somewhere introduced with the latest changes). And, by the way, neither this xml file nor previous version (before the PR applied) looks no good in the [SBGNViz](http://www.cs.bilkent.edu.tr/~ivis/SBGNViz_daily/) (and the "fixed" sbgn xml cannot even be opened in the NEWT). See the attached data files. Looks, this fix was not enough in this case; so I re-open this ticket.

I am going to try to fix that (division by 0) shortly...

**Comment by IgorRodchenkov** [comment]
Ah, I have to revert all the changes introduced with the PR #3, because its logic does not apply if noOfChildren is 0 (for either one node or or - both nodes A and B...); it produces NaN.

**Comment by ugurdogrusoz** [comment]
@hasanbalci In the java version, we might have compounds that are empty (no child) as opposed to the JS version, where that doesn't happen. Please investigate.

**Comment by hasanbalci** [comment]
Yes, the problem was that there can be compound nodes with no child in Java version, which I wasn't aware of since this is not the case in JS. Now, I fixed the problem in https://github.com/iVis-at-Bilkent/chilay/commit/60de0d2d6a8f977425913f9c9741bdcae7e0a226 and https://github.com/iVis-at-Bilkent/chilay/releases/latest. @IgorRodchenkov I also created a new PR #5. Could you please try it again? Thanks!

**Comment by IgorRodchenkov** [comment]
Thanks @ugurdogrusoz , @hasanbalci - fixed.
